apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/maas-api/overlays/tls  
  - ../../base/policies

patches:
  # Set HTTPS URL for tier lookup
  - target:
      group: kuadrant.io
      version: v1
      kind: AuthPolicy
      name: gateway-auth-policy
    patch: |-
      - op: replace
        path: /spec/rules/metadata/matchedTier/http/url
        value: https://maas-api.opendatahub.svc.cluster.local:8443/v1/tiers/lookup
      - op: replace
        path: /spec/rules/modelAccess/http/url
        value: https://maas-api.opendatahub.svc.cluster.local:8443/v1/models/authorize
    

